// Bandwidth Guardian — shared isolated-world helpers
//
// The early prehook runs in the page's MAIN world because JavaScript prototype
// patches made from an ISOLATED content-script world are not visible to the
// page's own JavaScript. This file remains ISOLATED so it can use chrome.* APIs.
//
// Settings are bridged to prehook.js with a tiny window.postMessage channel.
// The page can observe/interfere with MAIN-world code by design, so the bridge
// carries only non-secret extension configuration.

const BH_MAIN_CHANNEL = "__bandwidth_guardian_v1__";

const BH_DEFAULTS = {
  enabled:         true,
  proxyBase:       "",
  quality:         40,
  grayscale:       true,
  maxWidth:        1280,
  excludeDomains:  "google.com gstatic.com challenges.cloudflare.com",
  isWebpSupported: false,
};

// Tracking-pixel URL patterns (ported from the original bandwidth-hero's
// shouldCompress.js). These are path/host patterns, not editable exclusions.
const BH_TRACKING_PATTERNS = [
  /pagead/i,
  /(pixel|cleardot)[^/]*\.(gif|jpg|jpeg)/i,
  /google\.([a-z.]+)\/(ads|generate_204|.*\/log204)+/i,
  /google-analytics\.([a-z.]+)\/(r|collect)+/i,
  /youtube\.([a-z.]+)\/(api|ptracking|player_204|live_204)+/i,
  /doubleclick\.([a-z.]+)\/(pcs|pixel|r)+/i,
  /googlesyndication\.([a-z.]+)\/ddm/i,
  /pixel\.facebook\.([a-z.]+)/i,
  /facebook\.([a-z.]+)\/(impression\.php|tr)+/i,
  /ad\.bitmedia\.io/i,
  /yahoo\.([a-z.]+)\/pixel/i,
  /criteo\.net\/img/i,
  /ad\.doubleclick\.net/i
];

function bhSafeURL(u) {
  try { return new URL(u); } catch { return null; }
}

function bhResolveHttpURL(raw, base = document.baseURI || location.href) {
  const value = String(raw ?? "").trim();
  if (!value) return null;
  try {
    const u = new URL(value, base);
    return (u.protocol === "http:" || u.protocol === "https:") ? u : null;
  } catch {
    return null;
  }
}

function bhDomainSet(text) {
  if (text instanceof Set) return new Set(text);
  if (Array.isArray(text)) return new Set(text);
  return new Set(
    String(text || "").split(/[,\s]+/)
      .map(s => s.trim().toLowerCase()).filter(Boolean)
      .map(s => s.replace(/^https?:\/\//, "").split("/")[0])
      .map(s => s.replace(/^\*?\./, "").replace(/\.$/, ""))
      .filter(Boolean)
  );
}

function bhHostMatchesDomain(hostname, domainSet) {
  const host = String(hostname || "").toLowerCase().replace(/\.$/, "");
  if (!host) return false;
  for (const domain of domainSet) {
    if (host === domain || host.endsWith("." + domain)) return true;
  }
  return false;
}

let BH_EXCLUDE_SET = new Set();
const BH_PROXY_SIGNATURES = new Set();

function bhProxySignature(base) {
  const u = bhSafeURL(base);
  if (!u || (u.protocol !== "http:" && u.protocol !== "https:")) return "";
  return u.origin + u.pathname;
}

function bhRegisterProxyBase(base) {
  const signature = bhProxySignature(base);
  if (signature) BH_PROXY_SIGNATURES.add(signature);
}

function bhLooksLikeGeneratedProxy(url) {
  const u = bhSafeURL(url);
  if (!u || !u.searchParams.has("url")) return false;
  const signature = u.origin + u.pathname;
  if (!BH_PROXY_SIGNATURES.has(signature)) return false;
  // Require the parameters generated by bhBuildProxyUrl as well. This avoids
  // skipping an unrelated image merely because it shares the proxy host/path.
  return u.searchParams.has("quality") &&
         u.searchParams.has("bw") &&
         u.searchParams.has("jpeg");
}

// Single decision point for "leave this URL alone".
function bhShouldSkip(url, hostname, opts, pageHostname) {
  if (!opts) return false;
  if (opts.enabled === false) return true;

  const host = String(hostname || "").toLowerCase();
  if (bhHostMatchesDomain(host, BH_EXCLUDE_SET)) return true;
  if (pageHostname && bhHostMatchesDomain(pageHostname, BH_EXCLUDE_SET)) return true;
  if (bhLooksLikeGeneratedProxy(url)) return true;

  let path = String(url || "").toLowerCase();
  try {
    path = new URL(url, document.baseURI || location.href).pathname.toLowerCase();
  } catch {}
  if (path.endsWith(".ico") || path.endsWith(".svg")) return true;
  if (path.includes("favicon")) return true;
  if (BH_TRACKING_PATTERNS.some(p => p.test(String(url || "")))) return true;
  return false;
}

function bhIsValidProxyBase(base) {
  const u = bhSafeURL(String(base || "").trim());
  return !!u && (u.protocol === "http:" || u.protocol === "https:");
}

function bhBuildProxyUrl(orig, opts) {
  if (!opts || opts.enabled === false || !opts.proxyBase) return orig;

  const target = bhResolveHttpURL(orig);
  if (!target || bhShouldSkip(target.href, target.hostname, opts, location.hostname)) {
    return orig;
  }

  const base = String(opts.proxyBase).trim();
  if (!bhIsValidProxyBase(base)) return orig;

  try {
    const proxy = new URL(base);
    proxy.hash = "";

    const quality = Number.isInteger(Number(opts.quality)) &&
                    Number(opts.quality) >= 1 && Number(opts.quality) <= 100
      ? Math.round(Number(opts.quality))
      : 40;
    const maxWidth = Number.isInteger(Number(opts.maxWidth)) &&
                     Number(opts.maxWidth) >= 0
      ? Math.round(Number(opts.maxWidth))
      : 1280;

    proxy.searchParams.set("url", target.href);
    proxy.searchParams.set("jpeg", opts.isWebpSupported ? "0" : "1");
    proxy.searchParams.set("bw", opts.grayscale ? "1" : "0");
    proxy.searchParams.set("quality", String(quality));
    if (maxWidth > 0) proxy.searchParams.set("max_width", String(maxWidth));
    else proxy.searchParams.delete("max_width");

    return proxy.href;
  } catch {
    return orig;
  }
}

function bhNormalizeOpts(raw) {
  const d = raw && typeof raw === "object" ? raw : {};
  const proxyBase = String(d.proxyBase ?? "").trim();
  const quality = Number(d.quality);
  const maxWidth = Number(d.maxWidth);

  return {
    enabled:        d.enabled === undefined ? BH_DEFAULTS.enabled : d.enabled === true,
    proxyBase:      bhIsValidProxyBase(proxyBase) ? proxyBase : "",
    quality:        Number.isFinite(quality) && Number.isInteger(quality) && quality >= 1 && quality <= 100
                      ? quality : BH_DEFAULTS.quality,
    grayscale:      d.grayscale === undefined ? BH_DEFAULTS.grayscale : d.grayscale === true,
    maxWidth:       Number.isFinite(maxWidth) && Number.isInteger(maxWidth) && maxWidth >= 0
                      ? maxWidth : BH_DEFAULTS.maxWidth,
    excludeDomains: String(d.excludeDomains ?? BH_DEFAULTS.excludeDomains).trim(),
    isWebpSupported:
      d.isWebpSupported === undefined
        ? BH_DEFAULTS.isWebpSupported
        : d.isWebpSupported === true,
  };
}

function bhApplyOpts(raw) {
  BH_OPTS = bhNormalizeOpts(raw);
  BH_EXCLUDE_SET = bhDomainSet(BH_OPTS.excludeDomains);
  bhRegisterProxyBase(BH_OPTS.proxyBase);
}

function bhPublishMainWorld() {
  try {
    window.postMessage({
      channel: BH_MAIN_CHANNEL,
      type: "config",
      opts: BH_OPTS,
    }, "*");
  } catch {}
}

function bhHandleMainWorldRequest(event) {
  if (event.source !== window) return;
  const data = event.data;
  if (!data || data.channel !== BH_MAIN_CHANNEL || data.type !== "request") return;
  bhPublishMainWorld();
}

window.addEventListener("message", bhHandleMainWorldRequest, false);

// ── Shared options loader / subscription ────────────────────────────────────
let BH_OPTS  = null;
let BH_READY = false;

const BH_READY_CBS  = [];
const BH_CHANGE_CBS = [];

function bhOnReady(cb) {
  if (BH_READY) {
    try { cb(BH_OPTS); } catch {}
  } else {
    BH_READY_CBS.push(cb);
  }
}

function bhOnOptsChange(cb) {
  BH_CHANGE_CBS.push(cb);
}

function bhResolveReady() {
  BH_READY = true;
  const cbs = BH_READY_CBS.splice(0);
  cbs.forEach(cb => { try { cb(BH_OPTS); } catch {} });
  bhPublishMainWorld();
}

function bhNotifyChange() {
  bhPublishMainWorld();
  BH_CHANGE_CBS.forEach(cb => { try { cb(BH_OPTS); } catch {} });
}

// Try the fast local mirror first, then sync storage as the correctness
// fallback. The service worker normally keeps bhOpts current.
chrome.storage.local.get({ bhOpts: null }, d => {
  if (d.bhOpts) {
    bhApplyOpts(d.bhOpts);
    bhResolveReady();
  } else {
    chrome.storage.sync.get(BH_DEFAULTS, synced => {
      bhApplyOpts(synced);
      bhResolveReady();
      chrome.storage.local.set({ bhOpts: BH_OPTS }, () => {});
    });
  }
});

chrome.storage.onChanged?.addListener((changes, area) => {
  if (area === "local" && changes.bhOpts) {
    bhApplyOpts(changes.bhOpts.newValue || BH_DEFAULTS);
    if (!BH_READY) bhResolveReady(); else bhNotifyChange();
  } else if (area === "sync") {
    chrome.storage.sync.get(BH_DEFAULTS, synced => {
      bhApplyOpts(synced);
      chrome.storage.local.set({ bhOpts: BH_OPTS }, () => {});
      if (!BH_READY) bhResolveReady(); else bhNotifyChange();
    });
  }
});

